/* TYPES OF AFFINITY: 
TEXT
NUMERIC ( EITHER REAL OR INT VALUE )
INTEGER
REAL
BLOB

HOW IT WORKS?:
SO IF THE TABLE HAVE AFFINITY OF TEXT, AND WE HAVE LETS SAY INTEGER OF "10", IF WE PUT THE 10 INSIDE THE TABLE, IT WILL BE CONVERTED INTO TEXT
*/