/* APPLIES TO A PARTICULAR COLUMN, FOR EXAMPLE: TO MAKE SURE IT DOESN'T HAVE NULL VALUES
CHECK (FOR EXAMPLE: CHECK TO MAKE SURE THIS VALUE IS GREATER THAN 0)
DEFAULT (USE DEFAULT VALUE IF WE DIDNT SUPPLY A VALUE)
NOT NULL (CANT BE EMPTY TO THE COLUMN)
UNIQUE (MAKE SURE EVERY VALUE IN THE ROW UNIQUE)

#################################################
PRIMARY/FOREIGN KEY WILL ALWAYS BE (NOT NULL AND UNIQUE) AUTOMATICALLY
#################################################
*/