/* TO DELETE ALL ROW */
DELETE FROM "collections";

/* TO DELETE JUST 1 ROW OR CERTAIN FEW ROW*/
DELETE FROM "collections" WHERE "title" = 'Spring Outing';
DELETE FROM "collections" WHERE "acquired" IS NULL;
DELETE FROM "collections" WHERE "acquired" < '1909-01-01';

/* THIS TO DELETE ALL RELTAED STUFF FROM ALL DIFF TABLE */
/* FOR EXAMPLE, WE CANT DELETE AN ARTIST BECAUSE THE ID IS REFRENCED IN ANOTHER TABLE, SO WE CAN DELETE IT
FROM THE OTHER TABLE FIRST */
 
DELETE FROM "created" WHERE "artist_id" = (
    SELECT "id" FROM "artist" WHERE "name" - 'Unidentified Artist'
);

/* NOW WE CAN DELETE THE ARTIST FROM THE ARTIST TABLE */


/* CAN ADD ON DELETE = */
FOREIGN KEY("artist_id") REFERENCES "artist"("id")
    ON DELETE CASCADE

/* ADDING THIS WILL DELETE ALL THE AFFILIATION WHEN DELETED */
/* ALSO DELETING INSTANTLY FROM THE ARTIST TABLE WITH WHERE NAME = 'Unidentified Artist' WONT GIVE A CONSTRAINT ERROR ANYMORE */

