/* ORDER BY TAKES OUR QUERY RESULT AND ORDER IT */
SELECT "Title" . "Rating" FROM "Anything" ORDER BY "Rating" LIMIT 10;

/* ASC DESC */
SELECT "Title" . "Rating" FROM "Anything" ORDER BY "Rating" DESC;

/* AFTER BY RATING, THIS CAN DO VOTES TOO (BASCIALLY CAN DO MULTIPLE ORDER BY) */
SELECT "Title" . "Rating" FROM "Anything" ORDER BY "Rating" DESC, "Votes" DESC LIMIT 10;

/* THIS WILL SORT IT BASED ON THE ALPHABET */
SELECT "Title" FROM "Anything" ORDER BY "Title";



/* THSI MEANS ORDER AT COLUMN 1 DESC , CAN DO JUST THIS TO CHOOSE A CLUMN */
ORDER BY 1 desc 

