/* Storage Classes:  ( THIS ARE NOT DATA TYPES )
NULL
INTEGER
REAL
TEXT
BLOB ( BINARY LARGE OBJECT ) , REPRESENT THE DATA EXACTLY GIVEN TO IT
*/

/* STORAGE CLASS: 
INTEGER = 0-byte int to 8-byte int