/*
1) COMPILE TIME ERROR
2) RUNTIME ERROR
3) WARNINGS

1. HOW IT WORKS? CODE -> COMPILER -> BINARY EXECUTABLE FILE (BASCIALLY NORMAL ERROR AT THE TERMINAl)
2. LOGICAL ERROR, CAN CRASH IT
3. 
*/