/*
1. Braced Initialization, THIS USES {}
2. Functional Initialization, THIS USES () -> LESS SAFE THAN BRACED INITIALIZATION CUZ {} WONT ALLOW ERROR TO COMPILE 
3. Assignment Initialization, THIS USES =\

THE DIFFERENCE BETWEEN NO 1 AND 2 IS JUST:
NO1 WILL GIVE CMPILE ERROR IF U MAKE MISTAKE LIKE int dog {10,5}
NO2 WILL NOT GIVE COMPILE ERROR BUT JUST GONNA CHOP IT OFF TO {10}

*/
